# Shared core config for the 1.5 degree models.

data:
    dt: 6
    data_path: "PLACEHOLDER.zarr"           # set in the overlay!
    constant_masks_path: "/hkfs/work/workspace/scratch/xk5289-level_comparison/era5-levels-study/data/constant_masks_1p5"
    constant_masks: ["soil_type_normalized.npy", "topography_normalized.npy", "land_mask.npy"]
    normalization_dir: "PLACEHOLDER" # set in the overlay!
    train_time_range: ["2000-01-01", "2021-12-31"]
    valid_time_range: ["2022-01-01", "2022-12-31"]
    train_subset: -1
    valid_subset: -1
    dataset_subsampling: 1
    target_subsampling: 6
    prefetch_factor: 2
    num_workers: 4
    xlat: 120
    xlon: 240
    n_in_timesteps: 2
    n_out_timesteps: 1
    pressure_levels: [1000, 925, 850, 700, 600, 500, 400, 300, 250, 200, 150, 100, 50] # Override in overlay.

model:
    embedding_dimension: 512
    patch_size: 2
    n_attn_heads: [8, 16, 8]
    n_attn_blocks: [2, 3, 2]
    window_size_outer: [12, 30]
    window_size_inner: [10, 10]
    noise_dim: 32
    nice_norm: False
    latent_rollout: 1
    bayesian: False

training:
    tf32: True
    n_samples: 1
    n_epochs: 16
    batch_size: 1
    lr_scheduler: True
    low_lr: 0.00001
    normal_lr: 0.0001
    dtype: float32
    autocast: False
    timings: False
    checkpoint_interval: 1000
    flash_attn: True
    # dump_maps_vars: ["geopotential_500", "2m_temperature", "temperature_850"]

jigsaw:
    parallelism: 4
    type: jigsaw

mesh_dims: [1, 2, 1, 2, 2]
