# 13-level overlay for the 1.5deg model.
data:
    pressure_levels: [1000, 925, 850, 700, 600, 500, 400, 300, 250, 200, 150, 100, 50]
    data_path: "/hkfs/work/workspace/scratch/xk5289-level_comparison/data/era5_13level_1p5.zarr"
    normalization_dir: "/hkfs/work/workspace/scratch/xk5289-level_comparison/era5-levels-study/data/normalization/1p5/13"
